Repository crython-guardians/crython-client, pull requests merged in 2024-08, with the labels that each got.

#16 Ci: Vercel 배포 연동 (#13)
  build.sh
Labels: CI

#19 Feat/#15 메인 페이지 스크린 제작
  public/images/sample1.png
  public/images/sample2.png
  public/images/sample3.png
  public/pdf-icon.png
  src/components/common/RecentFileCard.tsx
  src/components/common/button/UploadButton.tsx
  src/components/common/input/SearchInput.tsx
  src/components/common/layout/DashboardLayout.styled.ts
  src/components/common/layout/DashboardLayout.tsx
  src/components/common/layout/Layout.tsx
  src/pages/auth/Auth.styled.ts
  src/pages/auth/LoginPage.tsx
  src/pages/auth/SignupPage.tsx
  src/pages/dashboard/DashboardPage.styled.ts
  src/pages/dashboard/DashboardPage.tsx
  src/pages/dashboard/DashboardTable.tsx
  src/pages/index.ts
  src/router/AppRouter.tsx
  src/styles/colors.ts
  src/styles/typography.ts
Labels: FEAT

#21 Feat/#8 파일 업로드 기능 개발 및 api 연동
  .gitignore
  src/components/common/button/UploadButton.tsx
  src/components/dashboard/RecentFileCard.tsx
  src/components/dashboard/SearchInput.tsx
  src/components/dashboard/UploadButton.tsx
  src/components/dashboard/layout/DashboardLayout.styled.ts
  src/components/dashboard/layout/DashboardLayout.tsx
  src/router/AppRouter.tsx
Labels: FEAT

#25 Feat/#9 회원가입/로그인 api 연동
  package.json
  src/pages/auth/LoginPage.tsx
  src/pages/auth/SignupPage.tsx
  src/services/apiClient.tsx
  src/services/auth/authApi.tsx
  src/services/file/fileApi.tsx
  yarn.lock
Labels: FEAT

#28 Style/#26 랜딩페이지 디자인 수정
  package.json
  src/pages/landing/LandingPage.styled.ts
  src/pages/landing/LandingPage.tsx
  src/services/apiClient.tsx
  src/services/auth/authApi.tsx
  yarn.lock
Labels: STYLE

#29 Feat/#17 파일 리스트 생성
  src/components/dashboard/RecentFileCard.tsx
  src/components/dashboard/fileList/FileList.tsx
  src/components/dashboard/fileList/FileListdataSource.ts
  src/components/dashboard/layout/DashboardLayout.styled.ts
  src/components/dashboard/layout/DashboardLayout.tsx
  src/pages/landing/LandingPage.styled.ts
Labels: FEAT

#30 Feat/#7 404 페이지 스크린 제작
  src/components/dashboard/UploadButton.tsx
  src/components/dashboard/fileList/FileList.tsx
  src/pages/404/NotFoundPage.styled.ts
  src/pages/404/NotFoundPage.tsx
  src/styles/colors.ts
Labels: FEAT

#31 Feat/#18 spinner 컴포넌트 생성 및 로딩 처리
  package.json
  src/components/common/spinner/Spinner.tsx
  src/components/common/spinner/SpinnerAnimation.json
  src/pages/landing/LandingPage.styled.ts
  yarn.lock
Labels: FEAT

#32 Feat/#27 add user
  src/pages/auth/LoginPage.tsx
  src/pages/auth/SignupPage.tsx
Labels: FEAT

#33 Feat/#20 업로드 된 파일 미리보기 스크린 및 기능 개발
  src/components/common/button/PdfIcon.tsx
  src/components/common/modal/ModalLayout.tsx
  src/components/dashboard/DownloadButton.tsx
  src/components/dashboard/FullScreenPreview.tsx
  src/components/dashboard/PreviewInfoModal.tsx
  src/components/dashboard/RecentFileCard.tsx
  src/components/dashboard/fileList/FileList.tsx
Labels: FEAT

#37 Feat/#34 엑세스 공유 관리 및 개별 문서 보안 리포트 모달 기능 구현
  src/components/dashboard/ActionMenuToggle.tsx
  src/components/dashboard/SearchInput.tsx
  src/components/dashboard/SecurityReportModal.tsx
  src/components/dashboard/ShareManagementModal.tsx
  src/components/dashboard/fileList/FileList.tsx
  src/components/dashboard/layout/DashboardLayout.styled.ts
Labels: FEAT

#42 Fix/#40 배포 에러 수정
  public/manifest.json
  src/services/apiClient.tsx
  vercel.json
Labels: FIX

#44 Feat/#36 파일 다운로드 기능 개발 및 api 연동
  src/components/dashboard/DownloadButton.tsx
  src/components/dashboard/FullScreenPreview.tsx
  src/components/dashboard/UploadButton.tsx
  src/services/apiClient.tsx
  tsconfig.json
Labels: FEAT

#45 Feat/#22 업로드한 파일 리스트 api 연동
  src/components/dashboard/DownloadButton.tsx
  src/components/dashboard/UploadButton.tsx
  src/components/dashboard/fileList/FileList.tsx
  src/services/file/fileApi.tsx
  src/utils/dateUtils.ts
  src/utils/sessionUtils.ts
Labels: FEAT

#46 Feat/#35 파일 삭제 기능 구현
  src/components/dashboard/ActionMenuToggle.tsx
  src/components/dashboard/FileDeleteConfirmModal.tsx
  src/components/dashboard/FullScreenPreview.tsx
  src/components/dashboard/PreviewInfoModal.tsx
  src/components/dashboard/fileList/FileList.tsx
  src/services/file/fileApi.tsx
  yarn.lock
Labels: FEAT

#48 Feat/#47 파일리스트 구조 리팩토링
  src/components/dashboard/fileList/FileListLayout.tsx
  src/components/dashboard/fileList/MyFileList.tsx
  src/components/dashboard/layout/DashboardLayout.tsx
  src/services/file/types.ts
  src/types/file.ts
Labels: FEAT

#50 docs: Update README.md (#49)
  README.md
Labels: DOCS
